---
apiVersion: v1
kind: Namespace
metadata:
  name: sealed-secrets
  annotations:
    openshift.io/display-name: "Sealed Secrets Operator"
    openshift.io/requester: admin
    argocd.argoproj.io/sync-wave: "1"