apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: sealed-secrets-operator-helm
  namespace: sealed-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  targetNamespaces:
  - sealed-secrets
