apiVersion: bitnami.com/v1alpha1
kind: SealedSecretController
metadata:
  name: sealed-secret-controller
  namespace: sealed-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  securityContext:
    runAsUser: ''
    fsGroup: ''